from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
import csv
from flask import Response, send_file


def generate_pdf_report(entry):
    """Generates a PDF for a specific medical entry."""
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)

    # Header
    p.setFont("Helvetica-Bold", 20)
    p.drawString(50, 750, "VitalMine Hospital System")
    p.setFont("Helvetica", 12)
    p.drawString(50, 735, "Clinical Decision Support Report")
    p.line(50, 725, 550, 725)

    # Patient Details
    p.drawString(50, 680, f"Patient Name: {entry.name.upper()}")
    p.drawString(50, 660, f"Date/Time: {entry.timestamp.strftime('%Y-%m-%d %H:%M')}")
    p.drawString(50, 640, f"Report ID: #{entry.id}")

    # Vitals
    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, 600, "Clinical Vitals:")
    p.setFont("Helvetica", 12)
    p.drawString(70, 580, f"• Temperature: {entry.temp} °C")
    p.drawString(70, 560, f"• Heart Rate: {entry.hr} bpm")
    p.drawString(70, 540, f"• Respiratory Rate: {entry.rr} /min")
    p.drawString(70, 520, f"• WBC Count: {entry.wbc} /mcL")

    # Risk Box
    p.rect(50, 430, 500, 70)
    p.setFont("Helvetica-Bold", 14)
    p.drawString(60, 480, "AI RISK ASSESSMENT:")

    if entry.status == "High":
        p.setFillColorRGB(1, 0, 0)
    elif entry.status == "Warning":
        p.setFillColorRGB(1, 0.5, 0)
    else:
        p.setFillColorRGB(0, 0.5, 0)

    p.drawString(230, 480, entry.status.upper())
    p.setFillColorRGB(0, 0, 0)

    p.setFont("Helvetica-Oblique", 12)
    p.drawString(60, 450, f"Recommendation: {entry.advice}")

    # Footer
    p.setFont("Helvetica", 10)
    p.drawString(
        50,
        100,
        "This report was generated by VitalMine AI. Please consult a physician.",
    )
    p.drawString(50, 50, "Signature: __________________________")

    p.showPage()
    p.save()

    buffer.seek(0)
    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"Report_{entry.name}_{entry.id}.pdf",
        mimetype="application/pdf",
    )


def generate_csv_report(all_entries):
    """Generates a CSV of all ward data."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(
        ["ID", "Timestamp", "Name", "Temp", "HR", "RR", "WBC", "Status", "Advice"]
    )
    for e in all_entries:
        writer.writerow(
            [e.id, e.timestamp, e.name, e.temp, e.hr, e.rr, e.wbc, e.status, e.advice]
        )
    output.seek(0)
    return Response(
        output,
        mimetype="text/csv",
        headers={"Content-Disposition": "attachment;filename=ward_report.csv"},
    )
